//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZgradaDbEntities : DbContext
    {
        public ZgradaDbEntities()
            : base("name=ZgradaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kompanije> Kompanije { get; set; }
        public virtual DbSet<KompanijeUpravitelji> KompanijeUpravitelji { get; set; }
        public virtual DbSet<PricuvaRezijeGodina> PricuvaRezijeGodina { get; set; }
        public virtual DbSet<PricuvaRezijeMjesec> PricuvaRezijeMjesec { get; set; }
        public virtual DbSet<PricuvaRezijeMjesec_PD> PricuvaRezijeMjesec_PD { get; set; }
        public virtual DbSet<PricuvaRezijeMjesec_PD_Pripadci> PricuvaRezijeMjesec_PD_Pripadci { get; set; }
        public virtual DbSet<PricuvaRezijeMjesec_Vlasnici> PricuvaRezijeMjesec_Vlasnici { get; set; }
        public virtual DbSet<PrihodiRashodi> PrihodiRashodi { get; set; }
        public virtual DbSet<PrihodiRashodi_Prihodi> PrihodiRashodi_Prihodi { get; set; }
        public virtual DbSet<Zgrade> Zgrade { get; set; }
        public virtual DbSet<Zgrade_PosebniDijelovi> Zgrade_PosebniDijelovi { get; set; }
        public virtual DbSet<Zgrade_PosebniDijelovi_PD> Zgrade_PosebniDijelovi_PD { get; set; }
        public virtual DbSet<Zgrade_PosebniDijelovi_PD_Pripadci> Zgrade_PosebniDijelovi_PD_Pripadci { get; set; }
        public virtual DbSet<Zgrade_PosebniDijelovi_VlasniciPeriod> Zgrade_PosebniDijelovi_VlasniciPeriod { get; set; }
        public virtual DbSet<Zgrade_PosebniDijelovi_VlasniciPeriod_Vlasnici> Zgrade_PosebniDijelovi_VlasniciPeriod_Vlasnici { get; set; }
        public virtual DbSet<Zgrade_Stanari> Zgrade_Stanari { get; set; }
        public virtual DbSet<vZgrade> vZgrade { get; set; }
    }
}
