//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZgradaDbEntities : DbContext
    {
        public ZgradaDbEntities()
            : base("name=ZgradaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Kompanije> Kompanije { get; set; }
        public virtual DbSet<KompanijeUpravitelji> KompanijeUpravitelji { get; set; }
        public virtual DbSet<PricuvaRezijeGodina> PricuvaRezijeGodina { get; set; }
        public virtual DbSet<PricuvaRezijeMjesec> PricuvaRezijeMjesec { get; set; }
        public virtual DbSet<PricuvaRezijeMjesec_PosebniDioChild> PricuvaRezijeMjesec_PosebniDioChild { get; set; }
        public virtual DbSet<PricuvaRezijeMjesec_PosebniDioChild_Povrsine> PricuvaRezijeMjesec_PosebniDioChild_Povrsine { get; set; }
        public virtual DbSet<PricuvaRezijeMjesec_PosebniDioChild_Pripadci> PricuvaRezijeMjesec_PosebniDioChild_Pripadci { get; set; }
        public virtual DbSet<PricuvaRezijeMjesec_Vlasnici> PricuvaRezijeMjesec_Vlasnici { get; set; }
        public virtual DbSet<PrihodiRashodi> PrihodiRashodi { get; set; }
        public virtual DbSet<PrihodiRashodi_Prihodi> PrihodiRashodi_Prihodi { get; set; }
        public virtual DbSet<PrihodiRashodi_Rashodi> PrihodiRashodi_Rashodi { get; set; }
        public virtual DbSet<Zgrade> Zgrade { get; set; }
        public virtual DbSet<Zgrade_PosebniDijeloviChild> Zgrade_PosebniDijeloviChild { get; set; }
        public virtual DbSet<Zgrade_PosebniDijeloviChild_Povrsine> Zgrade_PosebniDijeloviChild_Povrsine { get; set; }
        public virtual DbSet<Zgrade_PosebniDijeloviChild_Pripadci> Zgrade_PosebniDijeloviChild_Pripadci { get; set; }
        public virtual DbSet<Zgrade_PosebniDijeloviMaster> Zgrade_PosebniDijeloviMaster { get; set; }
        public virtual DbSet<Zgrade_PosebniDijeloviMaster_VlasniciPeriod> Zgrade_PosebniDijeloviMaster_VlasniciPeriod { get; set; }
        public virtual DbSet<Zgrade_PosebniDijeloviMaster_VlasniciPeriod_Vlasnici> Zgrade_PosebniDijeloviMaster_VlasniciPeriod_Vlasnici { get; set; }
        public virtual DbSet<Zgrade_Stanari> Zgrade_Stanari { get; set; }
        public virtual DbSet<vZgrade> vZgrade { get; set; }
    }
}
