//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KS
    {
        public int Id { get; set; }
        public int PricuvaGodId { get; set; }
        public int StanarId { get; set; }
        public Nullable<int> Mjesec { get; set; }
        public Nullable<int> Godina { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<decimal> Uplata { get; set; }
    
        public virtual PricuvaGod PricuvaGod { get; set; }
    }
}
