//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricuvaRezijeMjesec_Uplatnice
    {
        public int Id { get; set; }
        public Nullable<int> PricuvaRezijeMjesecId { get; set; }
        public int PosebniDioMasterId { get; set; }
        public int PlatiteljId { get; set; }
        public Nullable<int> PrimateljId { get; set; }
        public string TipDuga { get; set; }
        public string TipPlacanja { get; set; }
        public Nullable<decimal> UdioPricuva { get; set; }
        public Nullable<decimal> UdioRezije { get; set; }
        public Nullable<decimal> IznosRezije { get; set; }
        public Nullable<decimal> IznosPricuva { get; set; }
        public Nullable<System.DateTime> DatumRacuna { get; set; }
        public Nullable<System.DateTime> DatumIsporuke { get; set; }
        public Nullable<System.DateTime> DatumDospijeca { get; set; }
        public string JedMjera { get; set; }
        public string Opis { get; set; }
        public Nullable<decimal> JedCijena { get; set; }
        public Nullable<decimal> Kolicina { get; set; }
        public Nullable<decimal> Ukupno { get; set; }
        public string Napomena { get; set; }
        public string BrojRacuna { get; set; }
        public string PdfUrl { get; set; }
        public string UplatnicaPlatiteljPodaci { get; set; }
        public string UplatnicaPrimateljPodaci { get; set; }
        public Nullable<decimal> UplatnicaZaPlatiti { get; set; }
        public string UplatnicaIBANPrimatelja { get; set; }
        public string UplatnicaModel { get; set; }
        public string UplatnicaPozivNaBroj { get; set; }
        public string UplatnicaSifraNamjene { get; set; }
        public string UplatnicaOpis { get; set; }
        public Nullable<System.DateTime> UplatnicaDatumUplatnice { get; set; }
        public Nullable<System.DateTime> UplatnicaDatumDospijeca { get; set; }
    
        public virtual PricuvaRezijeMjesec PricuvaRezijeMjesec { get; set; }
    }
}
