//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricuvaRezijeGodina_StanjeOd
    {
        public int Id { get; set; }
        public int PrivuvaRezijeGodId { get; set; }
        public int PosebniDioMasterId { get; set; }
        public Nullable<decimal> StanjeOd { get; set; }
    
        public virtual PricuvaRezijeGodina PricuvaRezijeGodina { get; set; }
    }
}
