//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricuvaMj
    {
        public int Id { get; set; }
        public int PricuvaGodId { get; set; }
        public int StanId { get; set; }
        public int VlasnikId { get; set; }
        public int Mjesec { get; set; }
        public Nullable<decimal> DugPretplata { get; set; }
        public Nullable<decimal> Zaduzenje { get; set; }
        public Nullable<decimal> Uplaceno { get; set; }
        public Nullable<decimal> StanjeOd { get; set; }
    
        public virtual PricuvaGod PricuvaGod { get; set; }
    }
}
