//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricuvaRezijePosebniDioMasterPripadci
    {
        public int Id { get; set; }
        public int PricuvaRezijePosebniDioMasterId { get; set; }
        public Nullable<int> PripadakId { get; set; }
        public Nullable<decimal> Povrsina { get; set; }
        public Nullable<decimal> Koef { get; set; }
        public string Naziv { get; set; }
        public string Oznaka { get; set; }
    
        public virtual PricuvaRezijePosebniDioMasteri PricuvaRezijePosebniDioMasteri { get; set; }
    }
}
