//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricuvaRezijeMjesec_PosebniDioChild_Pripadci
    {
        public int Id { get; set; }
        public int PricuvaRezijeMjesecPosDioChildId { get; set; }
        public Nullable<decimal> Povrsina { get; set; }
        public Nullable<decimal> Koef { get; set; }
    }
}
