//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricuvaMj_VrstaObracuna
    {
        public int Id { get; set; }
        public int PricuvaGodId { get; set; }
        public Nullable<byte> TipObracunaMj1 { get; set; }
        public Nullable<byte> TipObracunaMj2 { get; set; }
        public Nullable<byte> TipObracunaMj3 { get; set; }
        public Nullable<byte> TipObracunaMj4 { get; set; }
        public Nullable<byte> TipObracunaMj5 { get; set; }
        public Nullable<byte> TipObracunaMj6 { get; set; }
        public Nullable<byte> TipObracunaMj7 { get; set; }
        public Nullable<byte> TipObracunaMj8 { get; set; }
        public Nullable<byte> TipObracunaMj9 { get; set; }
        public Nullable<byte> TipObracunaMj11 { get; set; }
        public Nullable<byte> TipObracunaMj12 { get; set; }
        public Nullable<byte> CijenaMj1 { get; set; }
        public Nullable<byte> CijenaMj2 { get; set; }
        public Nullable<byte> CijenaMj3 { get; set; }
        public Nullable<byte> CijenaMj4 { get; set; }
        public Nullable<byte> CijenaMj5 { get; set; }
        public Nullable<byte> CijenaMj6 { get; set; }
        public Nullable<byte> CijenaMj7 { get; set; }
        public Nullable<byte> CijenaMj8 { get; set; }
        public Nullable<byte> CijenaMj9 { get; set; }
        public Nullable<byte> CijenaMj10 { get; set; }
        public Nullable<byte> CijenaMj11 { get; set; }
        public Nullable<byte> CijenaMj12 { get; set; }
        public Nullable<byte> TipObracunaMj10 { get; set; }
    
        public virtual PricuvaGod PricuvaGod { get; set; }
    }
}
