//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricuvaRezijeMjesec_PD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PricuvaRezijeMjesec_PD()
        {
            this.PricuvaRezijeMjesec_PD_Pripadci = new HashSet<PricuvaRezijeMjesec_PD_Pripadci>();
        }
    
        public int Id { get; set; }
        public int PricuvaRezijeMjesecId { get; set; }
        public Nullable<int> PosebniDioId { get; set; }
        public Nullable<decimal> Povrsina { get; set; }
        public Nullable<decimal> Koef { get; set; }
        public Nullable<decimal> ObracunPricuvaCijenaSlobodanUnos { get; set; }
        public Nullable<int> ObracunRezijeBrojClanova { get; set; }
        public Nullable<decimal> ObracunRezijeCijenaSlobodanUnos { get; set; }
    
        public virtual PricuvaRezijeMjesec PricuvaRezijeMjesec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PricuvaRezijeMjesec_PD_Pripadci> PricuvaRezijeMjesec_PD_Pripadci { get; set; }
    }
}
