//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrihodiRashodi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrihodiRashodi()
        {
            this.PrihodiRashodi_Prihodi = new HashSet<PrihodiRashodi_Prihodi>();
        }
    
        public int Id { get; set; }
        public int ZgradaId { get; set; }
        public int Godina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrihodiRashodi_Prihodi> PrihodiRashodi_Prihodi { get; set; }
        public virtual Zgrade Zgrade { get; set; }
    }
}
