//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrihodiRashodi_Rashodi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrihodiRashodi_Rashodi()
        {
            this.PrihodiRashodi_Rashodi_Uplatnice = new HashSet<PrihodiRashodi_Rashodi_Uplatnice>();
        }
    
        public int Id { get; set; }
        public int PrihodiRashodiGodId { get; set; }
        public Nullable<int> PosebniDioMasterId { get; set; }
        public int Mjesec { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> RashodId { get; set; }
        public Nullable<decimal> Iznos { get; set; }
        public Nullable<bool> Placen { get; set; }
        public Nullable<System.DateTime> DatumPlacanja { get; set; }
        public Nullable<bool> PoslanoZaMjesec { get; set; }
        public Nullable<int> PrenesenIzMjeseca { get; set; }
        public string StatusSlanja { get; set; }
        public Nullable<System.DateTime> DatumSlanja { get; set; }
        public string PdfFileName { get; set; }
    
        public virtual PrihodiRashodi PrihodiRashodi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrihodiRashodi_Rashodi_Uplatnice> PrihodiRashodi_Rashodi_Uplatnice { get; set; }
    }
}
