//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stanovi_Pripadci
    {
        public int Id { get; set; }
        public int StanId { get; set; }
        public int PripadakIZgradaId { get; set; }
        public Nullable<decimal> Koef { get; set; }
        public Nullable<int> VrijediOdGod { get; set; }
        public Nullable<int> VrijediOdMjesec { get; set; }
        public Nullable<int> VrijediDoGod { get; set; }
        public Nullable<int> VrijediDoMjesec { get; set; }
        public Nullable<decimal> PovrsinaSaKef { get; set; }
    
        public virtual Stanovi Stanovi { get; set; }
    }
}
