//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stanovi_Stanari
    {
        public int Id { get; set; }
        public int StanId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string OIB { get; set; }
        public Nullable<decimal> Udjel { get; set; }
        public string Email { get; set; }
        public string UserGuid { get; set; }
    
        public virtual Stanovi Stanovi { get; set; }
    }
}
