//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgrade_PosebniDijelovi_PD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zgrade_PosebniDijelovi_PD()
        {
            this.Zgrade_PosebniDijelovi_PD_Pripadci = new HashSet<Zgrade_PosebniDijelovi_PD_Pripadci>();
        }
    
        public int Id { get; set; }
        public int ZgradaPosDioId { get; set; }
        public string Naziv { get; set; }
        public string Oznaka { get; set; }
        public Nullable<decimal> Povrsina { get; set; }
        public Nullable<decimal> Koef { get; set; }
        public string Napomena { get; set; }
        public Nullable<bool> Zatvoren { get; set; }
        public Nullable<int> ZatvorenGodina { get; set; }
        public Nullable<int> ZatvorenMjesec { get; set; }
        public Nullable<int> VrijediOdGodina { get; set; }
        public Nullable<int> VrijediOdMjesec { get; set; }
    
        public virtual Zgrade_PosebniDijelovi Zgrade_PosebniDijelovi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zgrade_PosebniDijelovi_PD_Pripadci> Zgrade_PosebniDijelovi_PD_Pripadci { get; set; }
    }
}
