//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgrade_Pripadci
    {
        public int Id { get; set; }
        public int ZgradaId { get; set; }
        public int PripadakId { get; set; }
        public string Naziv { get; set; }
        public decimal PovrsinaM2 { get; set; }
        public Nullable<decimal> PovrsinaPosto { get; set; }
        public string Napomena { get; set; }
    
        public virtual Zgrade Zgrade { get; set; }
    }
}
