//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgrade_DnevnikRada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zgrade_DnevnikRada()
        {
            this.Zgrade_DnevnikRadaDetails = new HashSet<Zgrade_DnevnikRadaDetails>();
        }
    
        public int Id { get; set; }
        public int ZgradaId { get; set; }
        public int Godina { get; set; }
        public int Mjesec { get; set; }
        public System.DateTime Datum { get; set; }
        public string Naslov { get; set; }
        public string Opis { get; set; }
        public Nullable<bool> Odradjeno { get; set; }
        public int UserId { get; set; }
    
        public virtual Zgrade Zgrade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zgrade_DnevnikRadaDetails> Zgrade_DnevnikRadaDetails { get; set; }
    }
}
