//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgrade_PosebniDijeloviChild_Povrsine
    {
        public int Id { get; set; }
        public int PosebniDioChildId { get; set; }
        public string Naziv { get; set; }
        public string Oznaka { get; set; }
        public Nullable<decimal> Povrsina { get; set; }
        public Nullable<decimal> Koef { get; set; }
        public Nullable<bool> Zatvoren { get; set; }
        public Nullable<int> ZatvorenGodina { get; set; }
        public Nullable<int> ZatvorenMjesec { get; set; }
        public Nullable<int> VrijediOdGodina { get; set; }
        public Nullable<int> VrijediOdMjesec { get; set; }
    
        public virtual Zgrade_PosebniDijeloviChild Zgrade_PosebniDijeloviChild { get; set; }
    }
}
