//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgrade_DnevnikRadaDetails
    {
        public int Id { get; set; }
        public int DnevnikRadaId { get; set; }
        public System.DateTime Datum { get; set; }
        public string Poruka { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Zgrade_DnevnikRada Zgrade_DnevnikRada { get; set; }
    }
}
