//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgrade_PosebniDijelovi_VlasniciPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zgrade_PosebniDijelovi_VlasniciPeriod()
        {
            this.Zgrade_PosebniDijelovi_VlasniciPeriod_Vlasnici = new HashSet<Zgrade_PosebniDijelovi_VlasniciPeriod_Vlasnici>();
        }
    
        public int Id { get; set; }
        public int PosebniDioId { get; set; }
        public int VrijediOdMjesec { get; set; }
        public int VrijediOdGodina { get; set; }
        public Nullable<int> VrijediDoMjesec { get; set; }
        public Nullable<int> VrijediDoGodina { get; set; }
    
        public virtual Zgrade_PosebniDijelovi Zgrade_PosebniDijelovi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zgrade_PosebniDijelovi_VlasniciPeriod_Vlasnici> Zgrade_PosebniDijelovi_VlasniciPeriod_Vlasnici { get; set; }
    }
}
