//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgrade_Stanari
    {
        public int Id { get; set; }
        public int ZgradaId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string OIB { get; set; }
        public string Email { get; set; }
        public string UserGuid { get; set; }
        public Nullable<bool> OglasnaPloca { get; set; }
        public Nullable<bool> DnevnikRada { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Pass { get; set; }
        public string Telefon { get; set; }
        public string Mobiltel { get; set; }
    
        public virtual Zgrade Zgrade { get; set; }
    }
}
