//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgradaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgrade_PricuvaMjesec
    {
        public int Id { get; set; }
        public int Godina { get; set; }
        public int Mjesec { get; set; }
        public int ZgradaId { get; set; }
        public int StanId { get; set; }
        public Nullable<int> VlasnikId { get; set; }
        public Nullable<short> ObracunTip { get; set; }
        public Nullable<decimal> DugPretplata { get; set; }
        public Nullable<decimal> Zaduzenje { get; set; }
        public Nullable<decimal> Uplaceno { get; set; }
        public Nullable<decimal> StanjeOdProslog { get; set; }
        public Nullable<decimal> ObracunTipM2 { get; set; }
        public Nullable<decimal> ObracunTipUkupno { get; set; }
    
        public virtual Zgrade Zgrade { get; set; }
    }
}
